### ISSUE TITLE
The TP instruction is not supported "~"

### ISSUE THREAD

**Issue by x1aoren** [LewMC/Essence#121]
### Please describe the bug

For example,/tp 111 111 111 can be executed, but /tp 111~111 cannot be executed

### Steps to reproduce the behavior

As mentioned above, it does not support "~"

### Server information:

Minecraft Version: 1.20.6
Server Implementation: luminol(Folia Fork) 
Essence Version: 1.6.0

### Please enter a link to your logs

[11:58:04 INFO]: bilibili_Ren issued server command: /tp 111 111 111
[11:58:31 INFO]: bilibili_Ren issued server command: /tp 111 ~ 111
[11:58:31 ERROR]: Command exception: /tp 111 ~ 111
org.bukkit.command.CommandException: Unhandled exception executing command 'tp' in plugin Essence v1.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2258) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2232) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2396) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1691) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "~"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.base/java.lang.Double.parseDouble(Double.java:792) ~[?:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.commands.teleportation.tp.TeleportCommand.onCommand(TeleportCommand.java:64) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 20 more

**Comment by lewmilburn** [comment]
@x1aoren Done! Closed by #122 - Snapshot available here: https://github.com/LewMC/Essence/actions/runs/9887175922
