### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by x1aoren** [LewMC/Essence#137]
### Please describe the bug

I don't know if it's because I changed the startup parameters or updated the server
TP players will receive error messages, but they can still transmit them

### Steps to reproduce the behavior

/tp player
Latest Luminol Server
startup parameter:
@echo off
set Xms=2G
set Xmx=2G
set jar=luminol-1.20.6-paperclip.jar
set goto_time=10
:1
java -Xms%Xms% -Xmx%Xmx% -jar %jar% nogui
timeout /t %goto_time%
goto 1

### Expected behavior

No error reported

### Server information:

Minecraft Version: 1.20.6
Server Implementation: Luminol(Folia Fork)
Essence Version: 1.6.0

### Please enter a link to your logs

[09:52:32 INFO]: bilibili_Ren issued server command: /tp bilibili_LD
[09:52:32 ERROR]: Command exception: /tp bilibili_LD
org.bukkit.command.CommandException: Unhandled exception executing command 'tp' in plugin Essence v1.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2258) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2232) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2396) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1691) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.lewmc.essence.folialib.wrapper.task.WrappedFoliaTask
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.impl.FoliaImplementation.wrapTask(FoliaImplementation.java:492) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.impl.FoliaImplementation.runAtEntityLater(FoliaImplementation.java:307) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.impl.FoliaImplementation.runAtEntityLater(FoliaImplementation.java:298) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.utils.TeleportUtil.doTeleport(TeleportUtil.java:177) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.commands.teleportation.tp.TeleportCommand.onCommand(TeleportCommand.java:124) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 20 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: zip file closed [in thread "Region Scheduler Thread #0"]
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[luminol-1.20.6.jar:1.20.6-DEV-e6027bd]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.wrapper.task.WrappedFoliaTask.<clinit>(WrappedFoliaTask.java:15) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.impl.FoliaImplementation.wrapTask(FoliaImplementation.java:492) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.impl.FoliaImplementation.runAtEntityLater(FoliaImplementation.java:307) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.folialib.impl.FoliaImplementation.runAtEntityLater(FoliaImplementation.java:298) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.utils.TeleportUtil.doTeleport(TeleportUtil.java:177) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at [E][基础][替代ess的插件]essence-1.6.0.jar/net.lewmc.essence.commands.teleportation.tp.TeleportCommand.onCommand(TeleportCommand.java:124) ~[[E][基础][替代ess的插件]essence-1.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 20 more

### Anything else?

Author, update quickly!!

**Comment by lewmilburn** [comment]
Hi, I'm not able to reproduce on the latest 1.6.1 snapshot so it may have already been fixed, you can download the snapshot [here](https://github.com/LewMC/Essence/actions/runs/9919858596). Please ensure you fully restart your server when updating Essence and do not use plugman to update the plugin. Thanks!

**Comment by lewmilburn** [comment]
Hi, after some further research this may be due to a corrupted jar, please try re-downloading Essence and change the jar file. Hopefully this should fix it!

**Comment by x1aoren** [comment]
It seems to have been resolved
There was indeed no such problem before, maybe it was because I directly hot loaded some plugins that caused problems on the server
After I restarted the server, it did not report any errors
