### ISSUE TITLE
[Feature request] Add folia & luminol support

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [LewMC/Essence#52]
### What feature would you like to request?

That's it, add folia support plz :>

### Are you able to help implement the feature?

none :>

### Is your feature request related to an existing bug or issue?

none

### Please enter any additional comments below.

I will keep giving folia test platfrom!

**Comment by lewmilburn** [comment]
> Is there a compatability issue between the two? What is Folia?

Folia is a new server software made by Paper, it changes a lot on the backend of servers so plugins won't run unless they're explicitly flagged to support it. There will probably have to be a few code changes in Essence but it won't break it or remove features for standard Bukkit/Spigot/Paper.

**Comment by lewmilburn** [comment]
[18:28:59 ERROR]: Could not pass event PlayerJoinEvent to Essence v1.4.0-SNAPSHOT
java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1314) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1263) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.teleport(CraftEntity.java:226) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at net.lewmc.essence.events.JoinEvent.onPlayerJoin(JoinEvent.java:64) ~[essence-1.4.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"ec6b172"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:438) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.lambda$handleConfigurationFinished$1(ServerConfigurationPacketListenerImpl.java:164) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1631) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by lewmilburn** [comment]
- [ ] Joining teleport: https://mclo.gs/U0cGcWn
  - [ ] Linked: player data not being created https://mclo.gs/UqbHV1j

**Comment by lewmilburn** [comment]
Due to the extensive use of multithreading within the plugin, it's unlikely that folia support will be ready any time soon.

**Comment by lewmilburn** [comment]
@xiaoyueyoqwq, are you still able to assist with testing? There's a preview build available at https://lewmc.net/plugin/essence that adds support for Folia. I've had to temporarily remove the random tp (/rtp) command but there's some new stuff in this version as well.

I've tested it locally on both folia and paper, and I've got it running on my friend's paper server so I've got that side of things covered, could do with some help testing on the folia side though on other setups!

**Comment by xiaoyueyoqwq** [comment]
> @xiaoyueyoqwq, are you still able to assist with testing? There's a preview build available at https://lewmc.net/plugin/essence that adds support for Folia. I've had to temporarily remove the random tp (/rtp) command but there's some new stuff in this version as well.
> 
> I've tested it locally on both folia and paper, and I've got it running on my friend's paper server so I've got that side of things covered, could do with some help testing on the folia side though on other setups!

Hey
Sorry for slow reply, of course I can keep helping test; If you had any problem just connect me on github or my email, in China I cannot recived discord message at first time (caused china gov already banned discord :(

**Comment by lewmilburn** [comment]
> > @xiaoyueyoqwq, are you still able to assist with testing? There's a preview build available at https://lewmc.net/plugin/essence that adds support for Folia. I've had to temporarily remove the random tp (/rtp) command but there's some new stuff in this version as well.
> > I've tested it locally on both folia and paper, and I've got it running on my friend's paper server so I've got that side of things covered, could do with some help testing on the folia side though on other setups!
> 
> Hey Sorry for slow reply, of course I can keep helping test; If you had any problem just contact me on github or my email, in China I cannot recived discord message at first time (caused china gov already banned discord :(

Thank you! If you find any issues let me know 😄

**Comment by lewmilburn** [comment]
@xiaoyueyoqwq I'm getting ready to release this version and just wanted to check in to see if you've encountered any issues. Thanks 😄

**Comment by xiaoyueyoqwq** [comment]
> @xiaoyueyoqwq I'm getting ready to release this version and just wanted to check in to see if you've encountered any issues. Thanks 😄 

Got it👍

**Comment by lewmilburn** [comment]
Closing as added in 1.4.0
